package com.student.AcademicYearDetails;

import java.util.List;

public class NewEditFaAcademicYearDetails {

	public Integer id;
	public String code;
	public String createdDateTime;
	public Integer defaultMonthsinAcademicYear;
	public Integer defaultTermsInAcademicYear;
	public Integer defaultWeeksInAcademicYear;
	public Integer defaultWeeksNonEnrollment;
	public Integer disburement10PctLoan;
	public Integer disbursement10PctPell;
	public Integer disbursement11PctLoan;
	public Integer disbursement11PctPell;
	public Integer disbursement12PctLoan;
	public Integer disbursement12PctPell;
	public Integer disbursement13PctLoan;
	public Integer disbursement13PctPell;
	public Integer disbursement14PctLoan;
	public Integer disbursement14PctPell;
	public Integer disbursement15PctLoan;
	public Integer disbursement15PctPell;
	public Integer disbursement16PctLoan;
	public Integer disbursement17PctLoan;
	public Integer disbursement18PctLoan;
	public Integer disbursement19PctLoan;
	public Integer disbursement1PctGrant;
	public Integer disbursement1PctLoan;
	public Integer disbursement1PctOther;
	public Integer disbursement1PctPell;
	public Integer disbursement1PctPerkins;
	public Integer disbursement1PctWorkStudy;
	public Integer disbursement20PctLoan;
	public Integer disbursement2PctGrant;
	public Integer disbursement2PctLoan;
	public Integer disbursement2PctOther;
	public Integer disbursement2PctPell;
	public Integer disbursement2PctPerkins;
	public Integer disbursement2PctWorkStudy;
	public Integer disbursement3PctGrant;
	public Integer disbursement3PctLoan;
	public Integer disbursement3PctOther;
	public Integer disbursement3PctPell;
	public Integer disbursement3PctPerkins;
	public Integer disbursement3PctWorkStudy;
	public Integer disbursement4PctGrant;
	public Integer disbursement4PctLoan;
	public Integer disbursement4PctOther;
	public Integer disbursement4PctPell;
	public Integer disbursement4PctPerkins;
	public Integer disbursement4PctWorkStudy;
	public Integer disbursement5PctGrant;
	public Integer disbursement5PctLoan;
	public Integer disbursement5PctOther;
	public Integer disbursement5PctPell;
	public Integer disbursement5PctPerkins;
	public Integer disbursement5PctWorkStudy;
	public Integer disbursement6PctGrant;
	public Integer disbursement6PctLoan;
	public Integer disbursement6PctOther;
	public Integer disbursement6PctPell;
	public Integer disbursement6PctPerkins;
	public Integer disbursement6PctWorkStudy;
	public Integer disbursement7PctLoan;
	public Integer disbursement7PctPell;
	public Integer disbursement8PctLoan;
	public Integer disbursement8PctPell;
	public Integer disbursement9PctLoan;
	public Object disbursement9PctPell;
	public Boolean isActive;
	public String lastModifiedDateTime;
	public Integer lastModifiedUserId;
	public String name;
	public Integer numberGrantDisbursements;
	public Integer numberLoanDisbursements;
	public Integer numberOtherDisbursements;
	public Integer numberPellDisbursements;
	public Integer numberPerkinsDisbursements;
	public Object numberWorkStudyDisbursements;
	public Object packagingMethodId;
	public String rowVersion;
	public String originalState;
	public String secureState;
	//public List<Object> extendedProperties = null;
	public Integer entityState;
	public List<NewEditfaFundSourceDisbursementsGridDatum> fundSourceDisbursementsGridData;

}
