package com.student.Configuration.TestCases;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.student.BaseClass.BaseClass;
import com.student.Campus.GetCampus;
import com.student.Campus.GetCampusPayload;
import com.student.Campus.NewEditCampusDetails;
import com.student.Campus.NewEditCampusEmailSetting;
import com.student.Campus.NewEditCampusPayload;
import com.student.Campus.NewEditCampuses;
import com.student.TestData.UtilClass;

public class TC007_CampusesECRUDTestCases extends BaseClass {

	ObjectMapper objMapper = new ObjectMapper();

	public static String id_responsepayload_data;
	public static String name_responsepayload_data;
	public static String rowVersion_responsepayload_data;
	public static Integer idcampusEmailSetting_responsepayload_data;
	public static String rowVersioncampusEmailSetting_responsepayload_data;
	public static Integer idcampusDetails_responsepayload_data;
	public static String rowVersioncampusDetails_responsepayload_data;

	@BeforeMethod
	public void SetUp() {

		String service_URL = "/api/commands/Common/Campus";

		initialization(service_URL);

	}

	@Test(priority = 1)
	public void CreateCampus() throws JsonProcessingException {

		NewEditCampusEmailSetting newEditCampusEmailSetting = new NewEditCampusEmailSetting();
		newEditCampusEmailSetting.id = 0;
		newEditCampusEmailSetting.campusId = 0;
		newEditCampusEmailSetting.createdDateTime = "0001/01/01 00:00:00";
		newEditCampusEmailSetting.emailAddress = null;
		newEditCampusEmailSetting.fromName = null;
		newEditCampusEmailSetting.isEmailFormat = true;
		newEditCampusEmailSetting.lastModifiedDateTime = "0001/01/01 00:00:00";
		newEditCampusEmailSetting.lastModifiedUserId = 0;
		newEditCampusEmailSetting.rowVersion = null;
		newEditCampusEmailSetting.originalState = "";
		newEditCampusEmailSetting.secureState = "";
		newEditCampusEmailSetting.entityState = 3;

		NewEditCampusDetails newEditCampusDetails = new NewEditCampusDetails();
		newEditCampusDetails.id = -1;
		newEditCampusDetails.campus = null;
		newEditCampusDetails.academicTranscriptConfigSettingId = null;
		newEditCampusDetails.allowEditingRt4NumDaysPrior = 0;
		newEditCampusDetails.athleteEligibilityYears = null;
		newEditCampusDetails.athleticAssociationCode = null;
		newEditCampusDetails.attendanceMessage = "Attendance cannot be posted for this student because revenue has already been posted for this period. Contact your administrator to override this restriction.";
		newEditCampusDetails.autoStipendExcludeStatusList = null;
		newEditCampusDetails.autoUnregisterCourseStatus = "";
		newEditCampusDetails.autoUnregisterStudentCourseStatusChangeReasonId = 0;
		newEditCampusDetails.businessOfficeStaffId = null;
		newEditCampusDetails.careerServicesStaffId = null;
		newEditCampusDetails.commonlineFolderPath = "";
		newEditCampusDetails.courseRefundPolicyId = null;
		newEditCampusDetails.createdDateTime = "2020/05/18 06:14:14";
		newEditCampusDetails.creditBalanceEvaluationScheduling = null;
		newEditCampusDetails.creditBalanceEvaluationTimeFrame = null;
		newEditCampusDetails.creditBalanceEvaluationType = null;
		newEditCampusDetails.creditConversion = null;
		newEditCampusDetails.daysAddLdaDeterminationDate = 0;
		newEditCampusDetails.daysAddToLda = 0;
		newEditCampusDetails.daysToPostRevenue = 0;
		newEditCampusDetails.defaultEnrollmentOnLedger = "C";
		newEditCampusDetails.directorAdmissionsStaffId = null;
		newEditCampusDetails.directorEducationStaffId = null;
		newEditCampusDetails.directorFaStaffId = null;
		newEditCampusDetails.disbursementCancelTaskTemplateId = null;
		newEditCampusDetails.dlCancelNotificationStaffId = null;
		newEditCampusDetails.doNotCallOverrideDocumentTypeId = null;
		newEditCampusDetails.duplicateEmployerCheckCampusGroupId = null;
		newEditCampusDetails.entranceInterviewDocumentTypeId = null;
		newEditCampusDetails.expectedRefundDropDateDays = 0;
		newEditCampusDetails.expectedRefundLdaDays = 0;
		newEditCampusDetails.expectedRefundOption = 0;
		newEditCampusDetails.ferpaGroupId = null;
		newEditCampusDetails.gpaCalcCreditType = null;
		newEditCampusDetails.gradeDecimalPrecision = 0;
		newEditCampusDetails.highSchoolEmailTaskTemplateId = null;
		newEditCampusDetails.highSchoolLetterTaskTemplateId = null;
		newEditCampusDetails.hourConversion = null;
		newEditCampusDetails.housingContractReport = null;
		newEditCampusDetails.incompleteGradeExpirationDays = null;
		newEditCampusDetails.inquiryDaysBasisDateCode = "L";
		newEditCampusDetails.inquiryDaysSinceBasisDate = 0;
		newEditCampusDetails.is1098TCampusInfoUsed = false;
		newEditCampusDetails.is1098TFiledElectronically = true;
		newEditCampusDetails.is1098TServicer = false;
		newEditCampusDetails.isAddDropForCurrentOrLoaCourses = false;
		newEditCampusDetails.isAddDropForDropStatus = false;
		newEditCampusDetails.isAdjFullyDisbAyLpNotAllowed = false;
		newEditCampusDetails.isAllCriteriaEvaluated = false;
		newEditCampusDetails.isApproveAwardVerified = false;
		newEditCampusDetails.isAssociateFulfillDpa = false;
		newEditCampusDetails.isAthleticAssociationMember = false;
		newEditCampusDetails.isAttendanceMessageCustomized = false;
		newEditCampusDetails.isAutoAddCourseSectionAllowed = false;
		newEditCampusDetails.isAutoAdjustChargesAddDropPeriod = false;
		newEditCampusDetails.isAutoMatchPrevented = false;
		newEditCampusDetails.isAutoStipendAuthorizationPrevented = false;
		newEditCampusDetails.isAutoStipendsUsed = false;
		newEditCampusDetails.isAutoUnregisteredDueToGrade = false;
		newEditCampusDetails.isAxFmIntegration = false;
		newEditCampusDetails.isAyLpNotification = false;
		newEditCampusDetails.isCatalogYearEnabled = false;
		newEditCampusDetails.isClassSectionContactHoursValidatedAgainstCourse = false;
		newEditCampusDetails.isCommonLineOriginationStatusAutoUpdated = false;
		newEditCampusDetails.isCompletedDropCoursesAssociated = false;
		newEditCampusDetails.isContractPrintingEnabled = false;
		newEditCampusDetails.isCostInPriceInfoIncluded = false;
		newEditCampusDetails.isCourseAutoUnregisteredOtherReason = false;
		newEditCampusDetails.isCustomGpa = false;
		newEditCampusDetails.isDebitBalFromPriorIncluded = false;
		newEditCampusDetails.isDisbursementCancelNotificationSent = false;
		newEditCampusDetails.isDlCancelNotificationState = false;
		newEditCampusDetails.isEarnedCreditsIncluded = false;
		newEditCampusDetails.isEditingRt4AmountsAllowed = false;
		newEditCampusDetails.isElectivePoolWarningDisplayedCourseReg = false;
		newEditCampusDetails.isFafsaParentContributionIndependentIncluded = false;
		newEditCampusDetails.isForeignSchool = false;
		newEditCampusDetails.isFsaFundsPriorPeriodChargesAllowed = false;
		newEditCampusDetails.isFundSourceOrderUsed = false;
		newEditCampusDetails.isGradeLevelPreReq = false;
		newEditCampusDetails.isHousingCodeOverrideIsir = false;
		newEditCampusDetails.isIndependentMidTermGradePosted = false;
		newEditCampusDetails.isInFieldOfStudyChecked = false;
		newEditCampusDetails.isInProgressGradeCalculated = false;
		newEditCampusDetails.isJobLocationEvaluated = false;
		newEditCampusDetails.isJobTitleEvaluated = false;
		newEditCampusDetails.isLastDateToWithdrawEnforced = false;
		newEditCampusDetails.isLastLeaseNotExpired = false;
		newEditCampusDetails.isLeaseExpiredIfSubsequentLeaseBilled = false;
		newEditCampusDetails.isLeaseExpiredOnEndDate = false;
		newEditCampusDetails.isLeaseOnEnrollmentTransferUpdated = false;
		newEditCampusDetails.isLoaBoundariesCheckEnabled = false;
		newEditCampusDetails.isMultiDisbRecalcEnabled = false;
		newEditCampusDetails.isMultipleDisbursementRuleEnabled = false;
		newEditCampusDetails.isNewStudentAddToSscr = false;
		newEditCampusDetails.isNoApplicantRecordCreatedOnPortal = false;
		newEditCampusDetails.isOverallCumGpaDisplayedOnDpa = false;
		newEditCampusDetails.isOverlapLoanPeriodUsed = false;
		newEditCampusDetails.isOverlappingTermAllowed = false;
		newEditCampusDetails.isPpnEfTitleIvNotification = false;
		newEditCampusDetails.isRefundCalculationAllowedForReentryStudent = false;
		newEditCampusDetails.isRegistrationBillDetailDefault = false;
		newEditCampusDetails.isRegistrationBillSummaryDefault = true;
		newEditCampusDetails.isReimportCommonLineResponseFileAllowed = false;
		newEditCampusDetails.isReleaseToGlAutomated = false;
		newEditCampusDetails.isReqRulesAppliedToCourseSearch = false;
		newEditCampusDetails.isRequiredToTakeAttendance = false;
		newEditCampusDetails.isRetakeFeeWaivedIfAfterCourseStart = false;
		newEditCampusDetails.isRetakeFeeWaivedIfFailGrade = false;
		newEditCampusDetails.isRetakeFeeWaiveedIfPassGrade = false;
		newEditCampusDetails.isRevenueRecognitionAutomated = false;
		newEditCampusDetails.isRt4IncludeStudentInRefund = false;
		newEditCampusDetails.isRt4IncludeStudentInRefundOverride = false;
		newEditCampusDetails.isSapAutomatedReviewEnabled = false;
		newEditCampusDetails.isScheduledPaymentDatesRestricted = false;
		newEditCampusDetails.isSelfRegistrationRestricted = false;
		newEditCampusDetails.isStudentAttestationAllowed = false;
		newEditCampusDetails.isStudentGpaDisplayedOnTranscript = false;
		newEditCampusDetails.isStudentPlusRefundIncludedRt4 = false;
		newEditCampusDetails.isStudentStaffordRefundIncludedRt4 = false;
		newEditCampusDetails.isTermConfirmationUsed = true;
		newEditCampusDetails.isTermInAyDatesUsed = false;
		newEditCampusDetails.isTermUnconfirmAutomated = true;
		newEditCampusDetails.isTitleIvEvaluationIncluded = false;
		newEditCampusDetails.isUnapprovedTransferCreditUsed = false;
		newEditCampusDetails.isUpdateStudentToActiveLoaSpnEnabled = false;
		newEditCampusDetails.isUsingMultipleInquiry = false;
		newEditCampusDetails.isWaitListingRestricted = false;
		newEditCampusDetails.isZeroOutExtraAyLpAllowed = false;
		newEditCampusDetails.lastModifiedDateTime = "2020/05/18 06:14:14";
		newEditCampusDetails.lastModifiedUserId = 0;
		newEditCampusDetails.ldwDay = "L";
		newEditCampusDetails.ldwPercentage = null;
		newEditCampusDetails.ldwWeekDefinition = "S";
		newEditCampusDetails.ldwWeekendDay = null;
		newEditCampusDetails.limitStipendAmountSetting = "S";
		newEditCampusDetails.maxDaysPastGradDateForScheduledPayment = 0;
		newEditCampusDetails.militaryDeploymentStudentGroupId = null;
		newEditCampusDetails.naturalDisasterStudentGroupId = null;
		newEditCampusDetails.notificationAyLpStaffId = null;
		newEditCampusDetails.notificationPpnEftTitleIvStaffId = null;
		newEditCampusDetails.notifyStaffId = null;
		newEditCampusDetails.nsldsWithdrawalStatusDateFlag = "";
		newEditCampusDetails.numberDaysPastExpirationDeadlineOverride = null;
		newEditCampusDetails.onlyAuthorCanEditAcademicYearComments = false;
		newEditCampusDetails.path1098T = null;
		newEditCampusDetails.phoneExtension1098T = null;
		newEditCampusDetails.phoneNumber1098T = null;
		newEditCampusDetails.presidentStaffId = null;
		newEditCampusDetails.preventScheduleStipendSetting = "S";
		newEditCampusDetails.preventStipendDisbursementSetting = "S";
		newEditCampusDetails.promissoryNoteReport = null;
		newEditCampusDetails.reexpectDisbursementTaskTemplateId = null;
		newEditCampusDetails.registrationSummaryIncludeNegativeBalance = true;
		newEditCampusDetails.registrationSummaryIncludePositiveBalance = true;
		newEditCampusDetails.registrationSummaryIncludeZeroBalance = true;
		newEditCampusDetails.remittanceCity = "";
		newEditCampusDetails.remittanceCountryId = null;
		newEditCampusDetails.remittancePostalCode = "";
		newEditCampusDetails.remittanceState = "";
		newEditCampusDetails.remittanceStreetAddress = "";
		newEditCampusDetails.reportingMethod1098T = "A";
		newEditCampusDetails.retakeFeeCourseStartAfterNumDays = null;
		newEditCampusDetails.rowVersion = null;
		newEditCampusDetails.rt4DaysAddedToDropDate = 45;
		newEditCampusDetails.runSapAfterStudentIsDropped = "N";
		newEditCampusDetails.sapCalcDaysAfterPaymentPeriodEnd = null;
		newEditCampusDetails.sapCalcDaysAfterTermEnd = null;
		newEditCampusDetails.transcriptLogoFilePath = null;
		newEditCampusDetails.transcriptPrintPath = null;
		newEditCampusDetails.voidClearedRefundStipendCheckSetting = null;
		newEditCampusDetails.originalState = "";
		newEditCampusDetails.secureState = "";
		newEditCampusDetails.entityState = 3;

		NewEditCampuses newEditCampuses = new NewEditCampuses();
		newEditCampuses.isFromCodPackaging = false;
		newEditCampuses.isExcludedCrmIntegration = false;
		newEditCampuses.residencyTypeId = null;
		newEditCampuses.isElectivePoolWarningDisplayedCourseReg = false;
		newEditCampuses.isUnapprovedTransferCreditUsed = false;
		newEditCampuses.id = -1;
		newEditCampuses.name = "JackSonCampus";
		newEditCampuses.url = "www.Campusmgmt.com";
		newEditCampuses.domainname = "Cmc";
		newEditCampuses.durationLoa = 9;
		newEditCampuses.addDropDateDaysOffset = 0;
		newEditCampuses.addDropDateEnforcementFlag = "N";
		newEditCampuses.applyPaymentsMethod = "M";
		newEditCampuses.arAcctIndex = null;
		newEditCampuses.attendancePolicy = null;
		newEditCampuses.attEntityIdentifierCode = null;
		newEditCampuses.attRfmsPellIdCode = "";
		newEditCampuses.campusLinkAmbassadorStudentSpendingLimit = -1;
		newEditCampuses.cancelDays = 0;
		newEditCampuses.cashieringTimeout = null;
		newEditCampuses.city = "";
		newEditCampuses.classScheduleNote = null;
		newEditCampuses.clearinghouseReportingFlag = null;
		newEditCampuses.clearingHouseWithdrawalDateFlag = null;
		newEditCampuses.cnReportRandomKey = null;
		newEditCampuses.code = "NEWC";
		newEditCampuses.countryId = 0;
		newEditCampuses.createdDateTime = "2020/05/18 06:14:14";
		newEditCampuses.currencySymbol = "$";
		newEditCampuses.currencySymbolPosition = 0;
		newEditCampuses.daysToAddToDodRefundDueDate = 0;
		newEditCampuses.defaultAcademicCalendar = "";
		newEditCampuses.defaultActiveSchoolStatusId = 0;
		newEditCampuses.defaultArAccount = null;
		newEditCampuses.defaultCreditHoursInAcademicYear = null;
		newEditCampuses.defaultEmployerGroupDays = 0;
		newEditCampuses.defaultfNumberPaymentPeriods = "";
		newEditCampuses.defaultNdsActiveSchoolStatusId = 0;
		newEditCampuses.defaultPaymentMethodology = "";
		newEditCampuses.defaultStudentGroupDays = null;
		newEditCampuses.defaultWeeksInAcademicYear = null;
		newEditCampuses.directLoanAttEntityIdCode = null;
		newEditCampuses.directLoanIdentifierCode = "";
		newEditCampuses.directLoanReportingEntityIdentifierCode = null;
		newEditCampuses.domainname = "";
		newEditCampuses.downloadDocumentPath = "";
		newEditCampuses.duplicateCheckCampusGroupId = null;
		newEditCampuses.duplicateCriteriaCheckDetailId = null;
		newEditCampuses.duplicateCriteriaStatusList = null;
		newEditCampuses.duplicateTaskTemplateId = null;
		newEditCampuses.durationLoa = 4;
		newEditCampuses.edePath = "";
		newEditCampuses.emailAddress = "";
		newEditCampuses.faAdminStaffId = null;
		newEditCampuses.fafsaExtractOption = "1";
		newEditCampuses.faxNumber = "";
		newEditCampuses.ffelIdentifierBranch = null;
		newEditCampuses.ffelIdentifierCode = null;
		newEditCampuses.firstCollegeChoice = null;
		newEditCampuses.generalLedgerExportFileDefinitionId = null;
		newEditCampuses.generalLedgerExportFilePath = null;
		newEditCampuses.generalLedgerLastReleaseDate = null;
		newEditCampuses.glCompanyNumber = null;
		newEditCampuses.glForeignExchangeGainAccountNumber = null;
		newEditCampuses.glForeignExchangeLossAccountNumber = null;
		newEditCampuses.glSystem = null;
		newEditCampuses.gradeLevelPromotionTaskTemplateId = null;
		newEditCampuses.greatPlainsBatchIdentifier = null;
		newEditCampuses.greatPlainsDynamicsPath = null;
		newEditCampuses.greatPlainsDynamicsPathIv = null;
		newEditCampuses.greatPlainsPath = null;
		newEditCampuses.greatPlainsPathIv = null;
		newEditCampuses.imageNowDbConnectString = null;
		newEditCampuses.imageNowPath = null;
		newEditCampuses.invoiceEmailSetting = null;
		newEditCampuses.isAcademicYearLoanPackagingAllowed = false;
		newEditCampuses.isAccountingAllowed = true;
		newEditCampuses.isActive = true;
		newEditCampuses.isAnticipatedGradeLevelPromotionEvaluated = false;
		newEditCampuses.isAuditApplyCreditAllowed = false;
		newEditCampuses.isCalendarDaysUsedAddDropDateDaysOffset = false;
		newEditCampuses.isCampusLinkAmbassadorUsed = false;
		newEditCampuses.isCashieringUsed = false;
		newEditCampuses.isChangeForCanceledDisbursementsAllowed = false;
		newEditCampuses.isClearinghouseUsed = false;
		newEditCampuses.isCreditCardDataRequired = true;
		newEditCampuses.isCreditSourceOrderAllowed = false;
		newEditCampuses.isCrmIntegrated = false;
		newEditCampuses.isCrmStudentEntryOverride = false;
		newEditCampuses.isCVueEmailClient = false;
		newEditCampuses.isDisbursementAllowedWithinSameMonth = false;
		newEditCampuses.isDisbursementAutoApproved = false;
		newEditCampuses.isDisbursementsAutoPosted = false;
		newEditCampuses.isDuplicateAutoProcessed = false;
		newEditCampuses.isEnrollmentAllowed = false;
		newEditCampuses.isEstimatedAwardOriginatedCertified = false;
		newEditCampuses.isFaReadyToSendRestricted = false;
		newEditCampuses.isFloatingTermUsed = false;
		newEditCampuses.isGlobalExceptionSecurity = false;
		newEditCampuses.isGradeLevelPromotionAutomated = false;
		newEditCampuses.isGradeRequiredDropCourse = false;
		newEditCampuses.isInternalCreditCardVerified = false;
		newEditCampuses.isInternationalStudentEnabled = false;
		newEditCampuses.isirCCodeStudentGroupId = null;
		newEditCampuses.isirImportMatchMethod = "F";
		newEditCampuses.isirVerificationStudentGroupId = null;
		newEditCampuses.isLabelReportUsed = null;
		newEditCampuses.isLdaRetained = false;
		newEditCampuses.isLdaUpdatedWithMakeUpDate = false;
		newEditCampuses.isLeadsAllowed = true;
		newEditCampuses.isMakeupHoursAllowed = false;
		newEditCampuses.isNdsEnrollmentAllowed = false;
		newEditCampuses.isOnlinePaymentAllowed = null;
		newEditCampuses.isOnlineRegistrationAllowed = false;
		newEditCampuses.isPackagedAmountLimitedToCoa = false;
		newEditCampuses.isPackagingNotAllowedWhenCoaIsZero = false;
		newEditCampuses.isPackagingNotAllowedWhenNoIsirOnFile = false;
		newEditCampuses.isPortalUsed = false;
		newEditCampuses.isPostDisbursementBatchWithExceptionAllowed = false;
		newEditCampuses.isReentryToActiveSet = false;
		newEditCampuses.isRefundCalcAutoApproved = false;
		newEditCampuses.isRefundProcessAutomate = false;
		newEditCampuses.isRegistrationBillForEnrolledCampus = false;
		newEditCampuses.isRegistrationSummaryEstimated = null;
		newEditCampuses.isReservationsAllowed = false;
		newEditCampuses.isRt4EditInstitutionalChargeAllowed = false;
		newEditCampuses.isRt4Refund30DayExemptOverride = true;
		newEditCampuses.isServicerTermRequired = false;
		newEditCampuses.isSevisEnabled = false;
		newEditCampuses.isStudentAddressPrintedOnRegistrationSummary = null;
		newEditCampuses.isStudentsAwardedWithRecalcEfc = false;
		newEditCampuses.isT4FundsIncludedInStandardCalc = false;
		newEditCampuses.isTermStartSet = false;
		newEditCampuses.isTitleIvAidOnlyUpdatedByServicer = null;
		newEditCampuses.isTitleIvCalcUsed = false;
		newEditCampuses.isTitleIvEarn100 = false;
		newEditCampuses.isTransactionPaymentDueDateAllowed = false;
		newEditCampuses.isTransferMoveFaEstimates = true;
		newEditCampuses.isWaitListAllowed = false;
		newEditCampuses.labelReportName = null;
		newEditCampuses.lastModifiedDateTime = "2020/05/18 06:14:14";
		newEditCampuses.lastModifiedUserId = 2238;
		newEditCampuses.maxReservationTermCredits = 0;
		newEditCampuses.maxWaitlistTermCredits = 0;
		newEditCampuses.minimumTransactionDate = null;
		newEditCampuses.moveBudget = "A";
		newEditCampuses.name = "NEWCAMPUS";
		newEditCampuses.numberOfLoaAllowed = 4;
		newEditCampuses.officialSchoolName = null;
		newEditCampuses.onlinePaymentUserId = null;
		newEditCampuses.opeIdentifier = null;
		newEditCampuses.overrideNotReqStatus = 1;
		newEditCampuses.packagingStatusPromotionId = null;
		newEditCampuses.packagingStatusPromotionTolerance = null;
		newEditCampuses.paymentPeriodChargesParentDocumentTypeId = null;
		newEditCampuses.paymentPeriodChargesStudentDocumentTypeId = null;
		newEditCampuses.paymentProcessorAccountId = null;
		newEditCampuses.pellIdentifierBranch = "";
		newEditCampuses.pellIdentifierCode = "";
		newEditCampuses.phoneNumber1 = "";
		newEditCampuses.phoneNumber2 = "";
		newEditCampuses.phoneNumber3 = "";
		newEditCampuses.postalCode = "";
		newEditCampuses.priorityResolution = "1";
		newEditCampuses.prospectInquiryFormTemplateId = 1;
		newEditCampuses.refundCalculationPolicyId = null;
		newEditCampuses.registrationSummaryComment = null;
		newEditCampuses.registrationSummaryDueDate = null;
		newEditCampuses.registrationSummaryIncludeAddDrop = null;
		newEditCampuses.registrationSummaryIncludeApproved = null;
		newEditCampuses.registrationSummaryIncludeEnrollInfo = null;
		newEditCampuses.registrationSummaryIncludeExpectedFunding = null;
		newEditCampuses.registrationSummaryIncludeExpectedFundingTerm = null;
		newEditCampuses.registrationSummaryIncludeLedgerCard = false;
		newEditCampuses.registrationSummaryIncludePending = null;
		newEditCampuses.registrationSummaryIncludeStudentBal = null;
		newEditCampuses.registrationSummaryIncludeSubsidiary = false;
		newEditCampuses.registrationSummaryPrintDueDate = null;
		newEditCampuses.registrationSummaryPrintSched = null;
		newEditCampuses.registrationSummaryStudentComment = null;
		newEditCampuses.regSumIdToPrint = null;
		newEditCampuses.reportServerPath = null;
		newEditCampuses.reservationExpirationMinutes = 0;
		newEditCampuses.reservationNotificationHours = 0;
		newEditCampuses.reservationOnlineRegConfirmMinutes = 0;
		newEditCampuses.retakeGpaCalc = "3";
		newEditCampuses.reveueLastRecognizedDate = null;
		newEditCampuses.rowVersion = null;
		newEditCampuses.rptEntityIdentifier = null;
		newEditCampuses.rptRfmsPellIdCode = "";
		newEditCampuses.serialNumber = null;
		newEditCampuses.servicerExportPath = null;
		newEditCampuses.servicerFaStaffId = null;
		newEditCampuses.servicerLastExtractDate = null;
		newEditCampuses.servicerLink = "";
		newEditCampuses.servicerSaStaffId = null;
		newEditCampuses.servicerSchoolCode = null;
		newEditCampuses.servicerSchoolNumber = null;
		newEditCampuses.servicerUserId = null;
		newEditCampuses.sponsorEmailTemplate = null;
		newEditCampuses.state = "";
		newEditCampuses.statusChangeDays = 30;
		newEditCampuses.streetAddress = "";
		newEditCampuses.streetAddress2 = "";
		newEditCampuses.studentEmailTemplate = null;
		newEditCampuses.tcc = null;
		newEditCampuses.tgNumber = "";
		newEditCampuses.timeBetweenLoa = 4;
		newEditCampuses.tin = null;
		newEditCampuses.titleIvCreditBalanceDocumentTypeId = null;
		newEditCampuses.titleIvCreditBalanceParentDocumentTypeId = null;
		newEditCampuses.titleIvInstChargesParentDocumentTypeId = null;
		newEditCampuses.titleIvInstChargesStudentDocumentTypeId = null;
		newEditCampuses.transferAllowQueue = false;
		newEditCampuses.transferDocumentReview = "A";
		newEditCampuses.transferFaTaskAssignStaff = "A";
		newEditCampuses.transferFaTaskStaffId = null;
		newEditCampuses.transferFaTaskTemplateId = null;
		newEditCampuses.transferModifyFees = "A";
		newEditCampuses.transferMonitoringHoldStudentGroupId = null;
		newEditCampuses.transferMonitoringStudentGroupId = null;
		newEditCampuses.transferMoveCourses = "P";
		newEditCampuses.transferMoveDateBilled = "A";
		newEditCampuses.transferMoveFa = "A";
		newEditCampuses.transferMoveLda = "A";
		newEditCampuses.transferMoveStartDate = "A";
		newEditCampuses.transferQueueProcessDate = "N";
		newEditCampuses.transferSaTaskAssignStaff = "A";
		newEditCampuses.transferSaTaskStaffId = null;
		newEditCampuses.transferSaTaskTemplateId = null;
		newEditCampuses.url = "";
		newEditCampuses.waitlistExpirationDays = 0;
		newEditCampuses.waitlistExpirationType = "ET";
		newEditCampuses.waitlistMaxNumberOfSeats = 0;
		newEditCampuses.waitlistMaxNumberOfSeatsType = "F";
		newEditCampuses.waitlistNotificatiobStudentAcceptedTaskTypeId = null;
		newEditCampuses.waitListNotificationMode = "A";
		newEditCampuses.waitlistNotificationStudentOfferedTaskTypeId = null;
		newEditCampuses.waitlistNotificationStudentRemovedTaskTypeId = null;
		newEditCampuses.originalState = "";
		newEditCampuses.secureState = "";
		newEditCampuses.entityState = 0;

		NewEditCampusPayload newEditCampusPayload = new NewEditCampusPayload();
		newEditCampusPayload.payload = newEditCampuses;

		List<NewEditCampusEmailSetting> newEditCampusEmailSettingList = new ArrayList<NewEditCampusEmailSetting>();
		newEditCampusEmailSettingList.add(newEditCampusEmailSetting);

		newEditCampusPayload.payload.campusEmailSetting = newEditCampusEmailSettingList;

		newEditCampusPayload.payload.campusDetails = newEditCampusDetails;

		String data = objMapper.writerWithDefaultPrettyPrinter().writeValueAsString(newEditCampusPayload);

		System.out.println(data);

		request.body(newEditCampusPayload);

		response = request.post("/SaveNew");

		body = response.getBody();

		jsonPathEvaluator = body.jsonPath();

		id_responsepayload_data = jsonPathEvaluator.getString("payload.data.id");

		id_NewCampus = id_responsepayload_data;

		name_responsepayload_data = jsonPathEvaluator.getString("payload.data.name");

		Assert.assertEquals(name_responsepayload_data, "NEWCAMPUS");

	}

	@Test(priority = 2)
	public void GetCampus() throws JsonProcessingException {

		GetCampus getCampus = new GetCampus();
		getCampus.id = (int) Math.round(Double.parseDouble(id_responsepayload_data));

		GetCampusPayload getCampusPayload = new GetCampusPayload();
		getCampusPayload.payload = getCampus;

		String data = objMapper.writerWithDefaultPrettyPrinter().writeValueAsString(getCampusPayload);

		System.out.println(data);

		request.body(getCampusPayload);

		response = request.post("/Get");

		body = response.getBody();

		jsonPathEvaluator = body.jsonPath();

		rowVersion_responsepayload_data = jsonPathEvaluator.getString("payload.data.rowVersion");

		idcampusEmailSetting_responsepayload_data = (Integer) jsonPathEvaluator
				.getList("payload.data.campusEmailSetting.id").get(0);

		rowVersioncampusEmailSetting_responsepayload_data = (String) jsonPathEvaluator
				.getList("payload.data.campusEmailSetting.rowVersion").get(0);

		idcampusDetails_responsepayload_data = jsonPathEvaluator.get("payload.data.campusDetails.id");

		rowVersioncampusDetails_responsepayload_data = jsonPathEvaluator.get("payload.data.campusDetails.rowVersion");

		Assert.assertEquals(response.getStatusCode(), 200);

	}

	@Test(priority = 3)
	public void EditCampus() throws JsonProcessingException {

		NewEditCampusEmailSetting newEditCampusEmailSetting = new NewEditCampusEmailSetting();
		newEditCampusEmailSetting.id = idcampusEmailSetting_responsepayload_data;
		newEditCampusEmailSetting.campusId = (int) Math.round(Double.parseDouble(id_responsepayload_data));
		newEditCampusEmailSetting.createdDateTime = "2020/05/20 00:11:43";
		newEditCampusEmailSetting.emailAddress = null;
		newEditCampusEmailSetting.fromName = null;
		newEditCampusEmailSetting.isEmailFormat = true;
		newEditCampusEmailSetting.lastModifiedDateTime = "2020/05/20 00:13:06";
		newEditCampusEmailSetting.lastModifiedUserId = 34719;
		newEditCampusEmailSetting.rowVersion = rowVersioncampusEmailSetting_responsepayload_data;
		newEditCampusEmailSetting.originalState = "";
		newEditCampusEmailSetting.secureState = "";
		newEditCampusEmailSetting.entityState = UtilClass.edit_entityState;

		NewEditCampusDetails newEditCampusDetails = new NewEditCampusDetails();
		newEditCampusDetails.id = idcampusDetails_responsepayload_data; // CampsuDetails id
		newEditCampusDetails.academicTranscriptConfigSettingId = null;
		newEditCampusDetails.allowEditingRt4NumDaysPrior = 0;
		newEditCampusDetails.athleteEligibilityYears = null;
		newEditCampusDetails.athleticAssociationCode = null;
		newEditCampusDetails.attendanceMessage = "Attendance cannot be posted for this student because revenue has already been posted for this period. Contact your administrator to override this restriction.";
		newEditCampusDetails.autoStipendExcludeStatusList = null;
		newEditCampusDetails.autoUnregisterCourseStatus = "";
		newEditCampusDetails.autoUnregisterStudentCourseStatusChangeReasonId = 0;
		newEditCampusDetails.businessOfficeStaffId = null;
		newEditCampusDetails.careerServicesStaffId = null;
		newEditCampusDetails.commonlineFolderPath = "";
		newEditCampusDetails.courseRefundPolicyId = null;
		newEditCampusDetails.createdDateTime = "2020/05/20 00:11:43";
		newEditCampusDetails.creditBalanceEvaluationScheduling = null;
		newEditCampusDetails.creditBalanceEvaluationTimeFrame = null;
		newEditCampusDetails.creditBalanceEvaluationType = null;
		newEditCampusDetails.creditConversion = null;
		newEditCampusDetails.daysAddLdaDeterminationDate = 0;
		newEditCampusDetails.daysAddToLda = 0;
		newEditCampusDetails.daysToPostRevenue = 0;
		newEditCampusDetails.defaultEnrollmentOnLedger = "C";
		newEditCampusDetails.directorAdmissionsStaffId = null;
		newEditCampusDetails.directorEducationStaffId = null;
		newEditCampusDetails.directorFaStaffId = null;
		newEditCampusDetails.disbursementCancelTaskTemplateId = null;
		newEditCampusDetails.dlCancelNotificationStaffId = null;
		newEditCampusDetails.doNotCallOverrideDocumentTypeId = null;
		newEditCampusDetails.duplicateEmployerCheckCampusGroupId = null;
		newEditCampusDetails.entranceInterviewDocumentTypeId = null;
		newEditCampusDetails.expectedRefundDropDateDays = 0;
		newEditCampusDetails.expectedRefundLdaDays = 0;
		newEditCampusDetails.expectedRefundOption = 0;
		newEditCampusDetails.ferpaGroupId = null;
		newEditCampusDetails.gpaCalcCreditType = null;
		newEditCampusDetails.gradeDecimalPrecision = 0;
		newEditCampusDetails.highSchoolEmailTaskTemplateId = null;
		newEditCampusDetails.highSchoolLetterTaskTemplateId = null;
		newEditCampusDetails.hourConversion = null;
		newEditCampusDetails.housingContractReport = null;
		newEditCampusDetails.incompleteGradeExpirationDays = null;
		newEditCampusDetails.inquiryDaysBasisDateCode = "L";
		newEditCampusDetails.inquiryDaysSinceBasisDate = 0;
		newEditCampusDetails.is1098TCampusInfoUsed = false;
		newEditCampusDetails.is1098TFiledElectronically = true;
		newEditCampusDetails.is1098TServicer = false;
		newEditCampusDetails.isAddDropForCurrentOrLoaCourses = false;
		newEditCampusDetails.isAddDropForDropStatus = false;
		newEditCampusDetails.isAdjFullyDisbAyLpNotAllowed = false;
		newEditCampusDetails.isAllCriteriaEvaluated = false;
		newEditCampusDetails.isApproveAwardVerified = false;
		newEditCampusDetails.isAssociateFulfillDpa = false;
		newEditCampusDetails.isAthleticAssociationMember = false;
		newEditCampusDetails.isAttendanceMessageCustomized = false;
		newEditCampusDetails.isAutoAddCourseSectionAllowed = false;
		newEditCampusDetails.isAutoAdjustChargesAddDropPeriod = false;
		newEditCampusDetails.isAutoMatchPrevented = false;
		newEditCampusDetails.isAutoStipendAuthorizationPrevented = false;
		newEditCampusDetails.isAutoStipendsUsed = false;
		newEditCampusDetails.isAutoUnregisteredDueToGrade = false;
		newEditCampusDetails.isAxFmIntegration = false;
		newEditCampusDetails.isAyLpNotification = false;
		newEditCampusDetails.isCatalogYearEnabled = false;
		newEditCampusDetails.isClassSectionContactHoursValidatedAgainstCourse = false;
		newEditCampusDetails.isCommonLineOriginationStatusAutoUpdated = false;
		newEditCampusDetails.isCompletedDropCoursesAssociated = false;
		newEditCampusDetails.isContractPrintingEnabled = false;
		newEditCampusDetails.isCostInPriceInfoIncluded = false;
		newEditCampusDetails.isCourseAutoUnregisteredOtherReason = false;
		newEditCampusDetails.isCustomGpa = false;
		newEditCampusDetails.isDebitBalFromPriorIncluded = false;
		newEditCampusDetails.isDisbursementCancelNotificationSent = false;
		newEditCampusDetails.isDlCancelNotificationState = false;
		newEditCampusDetails.isEarnedCreditsIncluded = false;
		newEditCampusDetails.isEditingRt4AmountsAllowed = false;
		newEditCampusDetails.isElectivePoolWarningDisplayedCourseReg = false;
		newEditCampusDetails.isFafsaParentContributionIndependentIncluded = false;
		newEditCampusDetails.isForeignSchool = false;
		newEditCampusDetails.isFsaFundsPriorPeriodChargesAllowed = false;
		newEditCampusDetails.isFundSourceOrderUsed = false;
		newEditCampusDetails.isGradeLevelPreReq = false;
		newEditCampusDetails.isHousingCodeOverrideIsir = false;
		newEditCampusDetails.isIndependentMidTermGradePosted = false;
		newEditCampusDetails.isInFieldOfStudyChecked = false;
		newEditCampusDetails.isInProgressGradeCalculated = false;
		newEditCampusDetails.isJobLocationEvaluated = false;
		newEditCampusDetails.isJobTitleEvaluated = false;
		newEditCampusDetails.isLastDateToWithdrawEnforced = false;
		newEditCampusDetails.isLastLeaseNotExpired = false;
		newEditCampusDetails.isLeaseExpiredIfSubsequentLeaseBilled = false;
		newEditCampusDetails.isLeaseExpiredOnEndDate = false;
		newEditCampusDetails.isLeaseOnEnrollmentTransferUpdated = false;
		newEditCampusDetails.isLoaBoundariesCheckEnabled = false;
		newEditCampusDetails.isMultiDisbRecalcEnabled = false;
		newEditCampusDetails.isMultipleDisbursementRuleEnabled = false;
		newEditCampusDetails.isNewStudentAddToSscr = false;
		newEditCampusDetails.isNoApplicantRecordCreatedOnPortal = false;
		newEditCampusDetails.isOverallCumGpaDisplayedOnDpa = false;
		newEditCampusDetails.isOverlapLoanPeriodUsed = false;
		newEditCampusDetails.isOverlappingTermAllowed = false;
		newEditCampusDetails.isPpnEfTitleIvNotification = false;
		newEditCampusDetails.isRefundCalculationAllowedForReentryStudent = false;
		newEditCampusDetails.isRegistrationBillDetailDefault = false;
		newEditCampusDetails.isRegistrationBillSummaryDefault = true;
		newEditCampusDetails.isReimportCommonLineResponseFileAllowed = false;
		newEditCampusDetails.isReleaseToGlAutomated = false;
		newEditCampusDetails.isReqRulesAppliedToCourseSearch = false;
		newEditCampusDetails.isRequiredToTakeAttendance = false;
		newEditCampusDetails.isRetakeFeeWaivedIfAfterCourseStart = false;
		newEditCampusDetails.isRetakeFeeWaivedIfFailGrade = false;
		newEditCampusDetails.isRetakeFeeWaiveedIfPassGrade = false;
		newEditCampusDetails.isRevenueRecognitionAutomated = false;
		newEditCampusDetails.isRt4IncludeStudentInRefund = false;
		newEditCampusDetails.isRt4IncludeStudentInRefundOverride = false;
		newEditCampusDetails.isSapAutomatedReviewEnabled = false;
		newEditCampusDetails.isScheduledPaymentDatesRestricted = false;
		newEditCampusDetails.isSelfRegistrationRestricted = false;
		newEditCampusDetails.isStudentAttestationAllowed = false;
		newEditCampusDetails.isStudentGpaDisplayedOnTranscript = false;
		newEditCampusDetails.isStudentPlusRefundIncludedRt4 = false;
		newEditCampusDetails.isStudentStaffordRefundIncludedRt4 = false;
		newEditCampusDetails.isTermConfirmationUsed = true;
		newEditCampusDetails.isTermInAyDatesUsed = false;
		newEditCampusDetails.isTermUnconfirmAutomated = true;
		newEditCampusDetails.isTitleIvEvaluationIncluded = false;
		newEditCampusDetails.isUnapprovedTransferCreditUsed = false;
		newEditCampusDetails.isUpdateStudentToActiveLoaSpnEnabled = false;
		newEditCampusDetails.isUsingMultipleInquiry = false;
		newEditCampusDetails.isWaitListingRestricted = false;
		newEditCampusDetails.isZeroOutExtraAyLpAllowed = false;
		newEditCampusDetails.lastModifiedDateTime = "2020/05/20 00:13:06";
		newEditCampusDetails.lastModifiedUserId = 34719;
		newEditCampusDetails.ldwDay = "L";
		newEditCampusDetails.ldwPercentage = null;
		newEditCampusDetails.ldwWeekDefinition = "S";
		newEditCampusDetails.ldwWeekendDay = null;
		newEditCampusDetails.limitStipendAmountSetting = "S";
		newEditCampusDetails.maxDaysPastGradDateForScheduledPayment = 0;
		newEditCampusDetails.militaryDeploymentStudentGroupId = null;
		newEditCampusDetails.naturalDisasterStudentGroupId = null;
		newEditCampusDetails.notificationAyLpStaffId = null;
		newEditCampusDetails.notificationPpnEftTitleIvStaffId = null;
		newEditCampusDetails.notifyStaffId = null;
		newEditCampusDetails.nsldsWithdrawalStatusDateFlag = "";
		newEditCampusDetails.numberDaysPastExpirationDeadlineOverride = null;
		newEditCampusDetails.onlyAuthorCanEditAcademicYearComments = false;
		newEditCampusDetails.path1098T = null;
		newEditCampusDetails.phoneExtension1098T = null;
		newEditCampusDetails.phoneNumber1098T = null;
		newEditCampusDetails.presidentStaffId = null;
		newEditCampusDetails.preventScheduleStipendSetting = "S";
		newEditCampusDetails.preventStipendDisbursementSetting = "S";
		newEditCampusDetails.promissoryNoteReport = null;
		newEditCampusDetails.reexpectDisbursementTaskTemplateId = null;
		newEditCampusDetails.registrationSummaryIncludeNegativeBalance = true;
		newEditCampusDetails.registrationSummaryIncludePositiveBalance = true;
		newEditCampusDetails.registrationSummaryIncludeZeroBalance = true;
		newEditCampusDetails.remittanceCity = "";
		newEditCampusDetails.remittanceCountryId = null;
		newEditCampusDetails.remittancePostalCode = "";
		newEditCampusDetails.remittanceState = "";
		newEditCampusDetails.remittanceStreetAddress = "";
		newEditCampusDetails.reportingMethod1098T = "A";
		newEditCampusDetails.retakeFeeCourseStartAfterNumDays = null;
		newEditCampusDetails.rowVersion = rowVersioncampusDetails_responsepayload_data; // CampusDetails rowVersion
		newEditCampusDetails.rt4DaysAddedToDropDate = 45;
		newEditCampusDetails.runSapAfterStudentIsDropped = "N";
		newEditCampusDetails.sapCalcDaysAfterPaymentPeriodEnd = null;
		newEditCampusDetails.sapCalcDaysAfterTermEnd = null;
		newEditCampusDetails.transcriptLogoFilePath = null;
		newEditCampusDetails.transcriptPrintPath = null;
		newEditCampusDetails.voidClearedRefundStipendCheckSetting = null;
		newEditCampusDetails.originalState = "";
		newEditCampusDetails.secureState = "";
		newEditCampusDetails.entityState = UtilClass.edit_entityState;

		NewEditCampuses newEditCampuses = new NewEditCampuses();
		newEditCampuses.isFromCodPackaging = false;
		newEditCampuses.isExcludedCrmIntegration = false;
		newEditCampuses.residencyTypeId = null;
		newEditCampuses.isElectivePoolWarningDisplayedCourseReg = false;
		newEditCampuses.isUnapprovedTransferCreditUsed = false;
		newEditCampuses.id = (int) Math.round(Double.parseDouble(id_responsepayload_data)); // Campus id
		newEditCampuses.addDropDateDaysOffset = 0;
		newEditCampuses.addDropDateEnforcementFlag = "N";
		newEditCampuses.applyPaymentsMethod = "M";
		newEditCampuses.arAcctIndex = null;
		newEditCampuses.attendancePolicy = null;
		newEditCampuses.attEntityIdentifierCode = "54545454";
		newEditCampuses.attRfmsPellIdCode = "545454";
		newEditCampuses.campusLinkAmbassadorStudentSpendingLimit = -1;
		newEditCampuses.cancelDays = 0;
		newEditCampuses.cashieringTimeout = null;
		newEditCampuses.city = "";
		newEditCampuses.classScheduleNote = null;
		newEditCampuses.clearinghouseReportingFlag = null;
		newEditCampuses.clearingHouseWithdrawalDateFlag = null;
		newEditCampuses.cnReportRandomKey = null;
		newEditCampuses.code = "NewCamps";
		newEditCampuses.countryId = 0;
		newEditCampuses.createdDateTime = "2020/05/20 00:11:43";
		newEditCampuses.currencySymbol = "$";
		newEditCampuses.currencySymbolPosition = 0;
		newEditCampuses.daysToAddToDodRefundDueDate = 0;
		newEditCampuses.defaultAcademicCalendar = "";
		newEditCampuses.defaultActiveSchoolStatusId = 13;
		newEditCampuses.defaultArAccount = null;
		newEditCampuses.defaultCreditHoursInAcademicYear = null;
		newEditCampuses.defaultEmployerGroupDays = 0;
		newEditCampuses.defaultfNumberPaymentPeriods = "";
		newEditCampuses.defaultNdsActiveSchoolStatusId = 60;
		newEditCampuses.defaultPaymentMethodology = "";
		newEditCampuses.defaultStudentGroupDays = null;
		newEditCampuses.defaultWeeksInAcademicYear = null;
		newEditCampuses.directLoanAttEntityIdCode = "54545454";
		newEditCampuses.directLoanIdentifierCode = "545454";
		newEditCampuses.directLoanReportingEntityIdentifierCode = "54545454";
		newEditCampuses.domainname = "";
		newEditCampuses.downloadDocumentPath = "";
		newEditCampuses.duplicateCheckCampusGroupId = null;
		newEditCampuses.duplicateCriteriaCheckDetailId = null;
		newEditCampuses.duplicateCriteriaStatusList = null;
		newEditCampuses.duplicateTaskTemplateId = null;
		newEditCampuses.durationLoa = 4;
		newEditCampuses.edePath = "\\inbnfs1\\Development";
		newEditCampuses.emailAddress = "";
		newEditCampuses.faAdminStaffId = null;
		newEditCampuses.fafsaExtractOption = "1";
		newEditCampuses.faxNumber = "";
		newEditCampuses.ffelIdentifierBranch = "54";
		newEditCampuses.ffelIdentifierCode = "545454";
		newEditCampuses.firstCollegeChoice = null;
		newEditCampuses.generalLedgerExportFileDefinitionId = null;
		newEditCampuses.generalLedgerExportFilePath = null;
		newEditCampuses.generalLedgerLastReleaseDate = null;
		newEditCampuses.glCompanyNumber = null;
		newEditCampuses.glForeignExchangeGainAccountNumber = null;
		newEditCampuses.glForeignExchangeLossAccountNumber = null;
		newEditCampuses.glSystem = null;
		newEditCampuses.gradeLevelPromotionTaskTemplateId = null;
		newEditCampuses.greatPlainsBatchIdentifier = null;
		newEditCampuses.greatPlainsDynamicsPath = null;
		newEditCampuses.greatPlainsDynamicsPathIv = null;
		newEditCampuses.greatPlainsPath = null;
		newEditCampuses.greatPlainsPathIv = null;
		newEditCampuses.imageNowDbConnectString = null;
		newEditCampuses.imageNowPath = null;
		newEditCampuses.invoiceEmailSetting = null;
		newEditCampuses.isAcademicYearLoanPackagingAllowed = false;
		newEditCampuses.isAccountingAllowed = true;
		newEditCampuses.isActive = true;
		newEditCampuses.isAnticipatedGradeLevelPromotionEvaluated = false;
		newEditCampuses.isAuditApplyCreditAllowed = false;
		newEditCampuses.isCalendarDaysUsedAddDropDateDaysOffset = false;
		newEditCampuses.isCampusLinkAmbassadorUsed = false;
		newEditCampuses.isCashieringUsed = false;
		newEditCampuses.isChangeForCanceledDisbursementsAllowed = false;
		newEditCampuses.isClearinghouseUsed = false;
		newEditCampuses.isCreditCardDataRequired = true;
		newEditCampuses.isCreditSourceOrderAllowed = false;
		newEditCampuses.isCrmIntegrated = false;
		newEditCampuses.isCrmStudentEntryOverride = false;
		newEditCampuses.isCVueEmailClient = false;
		newEditCampuses.isDisbursementAllowedWithinSameMonth = false;
		newEditCampuses.isDisbursementAutoApproved = false;
		newEditCampuses.isDisbursementsAutoPosted = false;
		newEditCampuses.isDuplicateAutoProcessed = false;
		newEditCampuses.isEnrollmentAllowed = true;
		newEditCampuses.isEstimatedAwardOriginatedCertified = false;
		newEditCampuses.isFaReadyToSendRestricted = false;
		newEditCampuses.isFloatingTermUsed = false;
		newEditCampuses.isGlobalExceptionSecurity = false;
		newEditCampuses.isGradeLevelPromotionAutomated = false;
		newEditCampuses.isGradeRequiredDropCourse = false;
		newEditCampuses.isInternalCreditCardVerified = false;
		newEditCampuses.isInternationalStudentEnabled = false;
		newEditCampuses.isirCCodeStudentGroupId = null;
		newEditCampuses.isirImportMatchMethod = "F";
		newEditCampuses.isirVerificationStudentGroupId = null;
		newEditCampuses.isLabelReportUsed = null;
		newEditCampuses.isLdaRetained = false;
		newEditCampuses.isLdaUpdatedWithMakeUpDate = false;
		newEditCampuses.isLeadsAllowed = true;
		newEditCampuses.isMakeupHoursAllowed = false;
		newEditCampuses.isNdsEnrollmentAllowed = false;
		newEditCampuses.isOnlinePaymentAllowed = null;
		newEditCampuses.isOnlineRegistrationAllowed = false;
		newEditCampuses.isPackagedAmountLimitedToCoa = false;
		newEditCampuses.isPackagingNotAllowedWhenCoaIsZero = false;
		newEditCampuses.isPackagingNotAllowedWhenNoIsirOnFile = false;
		newEditCampuses.isPortalUsed = false;
		newEditCampuses.isPostDisbursementBatchWithExceptionAllowed = false;
		newEditCampuses.isReentryToActiveSet = false;
		newEditCampuses.isRefundCalcAutoApproved = false;
		newEditCampuses.isRefundProcessAutomate = false;
		newEditCampuses.isRegistrationBillForEnrolledCampus = false;
		newEditCampuses.isRegistrationSummaryEstimated = null;
		newEditCampuses.isReservationsAllowed = false;
		newEditCampuses.isRt4EditInstitutionalChargeAllowed = false;
		newEditCampuses.isRt4Refund30DayExemptOverride = true;
		newEditCampuses.isServicerTermRequired = false;
		newEditCampuses.isSevisEnabled = false;
		newEditCampuses.isStudentAddressPrintedOnRegistrationSummary = null;
		newEditCampuses.isStudentsAwardedWithRecalcEfc = false;
		newEditCampuses.isT4FundsIncludedInStandardCalc = false;
		newEditCampuses.isTermStartSet = false;
		newEditCampuses.isTitleIvAidOnlyUpdatedByServicer = null;
		newEditCampuses.isTitleIvCalcUsed = false;
		newEditCampuses.isTitleIvEarn100 = false;
		newEditCampuses.isTransactionPaymentDueDateAllowed = false;
		newEditCampuses.isTransferMoveFaEstimates = true;
		newEditCampuses.isWaitListAllowed = false;
		newEditCampuses.labelReportName = null;
		newEditCampuses.lastModifiedDateTime = "2020/05/20 00:13:06";
		newEditCampuses.lastModifiedUserId = 34719;
		newEditCampuses.maxReservationTermCredits = 0;
		newEditCampuses.maxWaitlistTermCredits = 0;
		newEditCampuses.minimumTransactionDate = null;
		newEditCampuses.moveBudget = "A";
		newEditCampuses.name = "NewCampuses";
		newEditCampuses.numberOfLoaAllowed = 4;
		newEditCampuses.officialSchoolName = null;
		newEditCampuses.onlinePaymentUserId = null;
		newEditCampuses.opeIdentifier = "54545454";
		newEditCampuses.overrideNotReqStatus = 1;
		newEditCampuses.packagingStatusPromotionId = null;
		newEditCampuses.packagingStatusPromotionTolerance = null;
		newEditCampuses.paymentPeriodChargesParentDocumentTypeId = null;
		newEditCampuses.paymentPeriodChargesStudentDocumentTypeId = null;
		newEditCampuses.paymentProcessorAccountId = null;
		newEditCampuses.pellIdentifierBranch = "54";
		newEditCampuses.pellIdentifierCode = "545454";
		newEditCampuses.phoneNumber1 = "";
		newEditCampuses.phoneNumber2 = "";
		newEditCampuses.phoneNumber3 = "";
		newEditCampuses.postalCode = "";
		newEditCampuses.priorityResolution = "1";
		newEditCampuses.prospectInquiryFormTemplateId = 1;
		newEditCampuses.refundCalculationPolicyId = null;
		newEditCampuses.registrationSummaryComment = null;
		newEditCampuses.registrationSummaryDueDate = null;
		newEditCampuses.registrationSummaryIncludeAddDrop = null;
		newEditCampuses.registrationSummaryIncludeApproved = null;
		newEditCampuses.registrationSummaryIncludeEnrollInfo = null;
		newEditCampuses.registrationSummaryIncludeExpectedFunding = null;
		newEditCampuses.registrationSummaryIncludeExpectedFundingTerm = null;
		newEditCampuses.registrationSummaryIncludeLedgerCard = false;
		newEditCampuses.registrationSummaryIncludePending = null;
		newEditCampuses.registrationSummaryIncludeStudentBal = null;
		newEditCampuses.registrationSummaryIncludeSubsidiary = false;
		newEditCampuses.registrationSummaryPrintDueDate = null;
		newEditCampuses.registrationSummaryPrintSched = null;
		newEditCampuses.registrationSummaryStudentComment = null;
		newEditCampuses.regSumIdToPrint = null;
		newEditCampuses.reportServerPath = null;
		newEditCampuses.reservationExpirationMinutes = 0;
		newEditCampuses.reservationNotificationHours = 0;
		newEditCampuses.reservationOnlineRegConfirmMinutes = 0;
		newEditCampuses.retakeGpaCalc = "3";
		newEditCampuses.reveueLastRecognizedDate = null;
		newEditCampuses.rowVersion = rowVersion_responsepayload_data; // Campus rowVersion
		newEditCampuses.rptEntityIdentifier = "54545454";
		newEditCampuses.rptRfmsPellIdCode = "545454";
		newEditCampuses.serialNumber = "545454";
		newEditCampuses.servicerExportPath = null;
		newEditCampuses.servicerFaStaffId = null;
		newEditCampuses.servicerLastExtractDate = null;
		newEditCampuses.servicerLink = "";
		newEditCampuses.servicerSaStaffId = null;
		newEditCampuses.servicerSchoolCode = null;
		newEditCampuses.servicerSchoolNumber = null;
		newEditCampuses.servicerUserId = null;
		newEditCampuses.sponsorEmailTemplate = null;
		newEditCampuses.state = "";
		newEditCampuses.statusChangeDays = 30;
		newEditCampuses.streetAddress = "";
		newEditCampuses.streetAddress2 = "";
		newEditCampuses.studentEmailTemplate = null;
		newEditCampuses.tcc = null;
		newEditCampuses.tgNumber = "TG54545";
		newEditCampuses.timeBetweenLoa = 4;
		newEditCampuses.tin = null;
		newEditCampuses.titleIvCreditBalanceDocumentTypeId = null;
		newEditCampuses.titleIvCreditBalanceParentDocumentTypeId = null;
		newEditCampuses.titleIvInstChargesParentDocumentTypeId = null;
		newEditCampuses.titleIvInstChargesStudentDocumentTypeId = null;
		newEditCampuses.transferAllowQueue = false;
		newEditCampuses.transferDocumentReview = "A";
		newEditCampuses.transferFaTaskAssignStaff = "A";
		newEditCampuses.transferFaTaskStaffId = null;
		newEditCampuses.transferFaTaskTemplateId = null;
		newEditCampuses.transferModifyFees = "A";
		newEditCampuses.transferMonitoringHoldStudentGroupId = null;
		newEditCampuses.transferMonitoringStudentGroupId = null;
		newEditCampuses.transferMoveCourses = "P";
		newEditCampuses.transferMoveDateBilled = "A";
		newEditCampuses.transferMoveFa = "A";
		newEditCampuses.transferMoveLda = "A";
		newEditCampuses.transferMoveStartDate = "A";
		newEditCampuses.transferQueueProcessDate = "N";
		newEditCampuses.transferSaTaskAssignStaff = "A";
		newEditCampuses.transferSaTaskStaffId = null;
		newEditCampuses.transferSaTaskTemplateId = null;
		newEditCampuses.url = "";
		newEditCampuses.waitlistExpirationDays = 0;
		newEditCampuses.waitlistExpirationType = "ET";
		newEditCampuses.waitlistMaxNumberOfSeats = 0;
		newEditCampuses.waitlistMaxNumberOfSeatsType = "F";
		newEditCampuses.waitlistNotificatiobStudentAcceptedTaskTypeId = null;
		newEditCampuses.waitListNotificationMode = "A";
		newEditCampuses.waitlistNotificationStudentOfferedTaskTypeId = null;
		newEditCampuses.waitlistNotificationStudentRemovedTaskTypeId = null;
		newEditCampuses.originalState = "";
		newEditCampuses.secureState = "";
		newEditCampuses.entityState = UtilClass.edit_entityState;

		NewEditCampusPayload newEditCampusPayload = new NewEditCampusPayload();
		newEditCampusPayload.payload = newEditCampuses;

		List<NewEditCampusEmailSetting> newEditCampusEmailSettingList = new ArrayList<NewEditCampusEmailSetting>();
		newEditCampusEmailSettingList.add(newEditCampusEmailSetting);

		newEditCampusPayload.payload.campusEmailSetting = newEditCampusEmailSettingList;

		newEditCampusPayload.payload.campusDetails = newEditCampusDetails;

		String data = objMapper.writerWithDefaultPrettyPrinter().writeValueAsString(newEditCampusPayload);

		System.out.println(data);

		request.body(newEditCampusPayload);

		response = request.post("/Save");

		body = response.getBody();

		jsonPathEvaluator = body.jsonPath();

		Assert.assertEquals(response.getStatusCode(), 200);

	}

	@Test(priority = 4)
	public void DeleteCampus() throws JsonProcessingException, SQLException {

		String delete_quarySaPaymentApplyOrder = "delete from SaPaymentApplyOrder where sycampusid="
				+ id_responsepayload_data;

		DeleteQuaryfromDatabase(delete_quarySaPaymentApplyOrder);

		String delete_SyServiceExceptionCampusProperty = "delete from SyServiceExceptionCampusProperty where sycampusid="
				+ id_responsepayload_data;

		DeleteQuaryfromDatabase(delete_SyServiceExceptionCampusProperty);

		String delete_SyCampus = "delete from sycampus where sycampusid=" + id_responsepayload_data;

		DeleteQuaryfromDatabase(delete_SyCampus);

	}

}
